// Generated by CoffeeScript 1.4.0
var helloCtrl;

helloCtrl = (function() {

  function helloCtrl(view) {
    this.view = view;
  }

  helloCtrl.prototype.activate = function() {
    return this.view.show;
  };

  helloCtrl.prototype.deactivate = function() {
    return this.view.hide;
  };

  helloCtrl.prototype.init = function() {};

  return helloCtrl;

})();
