// Generated by CoffeeScript 1.4.0
var loadingCtrl;

loadingCtrl = (function() {

  function loadingCtrl(view) {
    this.view = view;
  }

  loadingCtrl.prototype.activate = function() {
    return this.view.show;
  };

  loadingCtrl.prototype.deactivate = function() {
    return this.view.hide;
  };

  loadingCtrl.prototype.init = function() {};

  return loadingCtrl;

})();
