// Generated by CoffeeScript 1.4.0
var HelloView;

HelloView = (function() {

  function HelloView(el) {
    if (typeof el === 'object') {
      this.el = el;
    } else {
      throw "" + el + " n'est pas un objet jQuery";
    }
  }

  HelloView.prototype.show = function() {
    return this.el.show;
  };

  HelloView.prototype.hide = function() {
    return this.el.hide;
  };

  return HelloView;

})();
