// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var helloView;
  return helloView = (function() {

    function helloView(el) {
      this.el = el;
      this.el = el;
    }

    helloView.prototype.show = function() {
      return $("" + this.el).show();
    };

    helloView.prototype.hide = function() {
      return $("" + this.el).hide();
    };

    return helloView;

  })();
});
