// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var loadingView;
  return loadingView = (function() {

    function loadingView(el) {
      this.el = el;
      this.el = el;
    }

    loadingView.prototype.show = function() {
      return $("" + this.el).show;
    };

    loadingView.prototype.hide = function() {
      return $("" + this.el).hide();
    };

    return loadingView;

  })();
});
