// Generated by CoffeeScript 1.4.0
var loadingView;

loadingView = (function() {

  function loadingView(el) {
    if (typeof el === 'object') {
      this.el = el;
    } else {
      throw "" + el + " n'est pas un objet jQuery";
    }
  }

  loadingView.prototype.show = function() {
    return this.el.show;
  };

  loadingView.prototype.hide = function() {
    return this.el.hide;
  };

  return loadingView;

})();
