// Generated by CoffeeScript 1.4.0

define(["jquery", "application/controllers/loading", "application/views/loadingView", "application/controllers/hello", "application/views/helloView"], function($, loadingCtrl, loadingView, helloCtrl, helloView) {
  var Application;
  return Application = (function() {

    function Application() {}

    Application.prototype.init = function() {
      var _this = this;
      this.helloCtrl = new helloCtrl(new helloView("#hello"));
      this.loadingCtrl = new loadingCtrl(new loadingView("#loading"));
      this.helloCtrl.deactivate();
      this.loadingCtrl.init();
      return $("#loading").bind('load', function(e) {
        return _this.helloCtrl.activate();
      });
    };

    return Application;

  })();
});
