// Generated by CoffeeScript 1.4.0

define(["jquery", "scripts/application/controllers/loading", "scripts/application/views/loadingView", "scripts/application/controllers/hello", "scripts/application/views/helloView"], function($, loading, loadingView, hello, helloView) {
  var Application;
  return Application = (function() {

    function Application() {}

    Application.prototype.init = function() {
      return console.log("hello world I have finished loading");
    };

    return Application;

  })();
});
