// Generated by CoffeeScript 1.4.0

define(["jquery", "application/controllers/loading", "application/views/loadingView", "application/controllers/hello", "application/views/helloView"], function($, loadingCtrl, loadingView, helloCtrl, helloView) {
  var Application;
  return Application = (function() {

    function Application() {}

    Application.prototype.init = function() {
      this.loadingCtrl = new loadingCtrl(new loadingView("#loading"));
      this.helloCtrl = new helloCtrl(new helloView("#hello"));
      this.loadingCtrl.init();
      return $("#loading").bind('click', function() {
        return console.log("I hide");
      });
    };

    return Application;

  })();
});
